Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo

- Algebra/Sieve_of_Eratosthenes.py
Added the code for the Sieve_Of_Eratosthenes
Resolving the issue (#30 )
> Sieve_Of_Eratosthenes (#30)

- String/Longest-Palindromic-Substring.py
Longest Palindromic Substring
Issue #40
> longest palindromic substring added

- String/LongestCommonSubstring.py
Added the code for Longest Common Substring 
Resolving Issue #21
> longestCommonSubstring added

- Topic Wise Questions with Solutions/Array/max_min.py
> added maximim and minimum of array

- String/Chech_if_string_contains_all_Binar_codes_of_size_k/check_for_all_binary_codes.py
- String/Chech_if_string_contains_all_Binar_codes_of_size_k/readme.txt
> Added solution to a strings problem

- Dynamic Programming/LIS_Length.py
- Dynamic Programming/fibonacci.py
I have created a new folder of Dynamic Programming in which l have added two program codes- Fibonacci and Longest Increasing Subsequence Length. Kindly check and merge the pull request.
Thank you!
> Fibonacci and LIS_length added( #43) (GSSOC'21)

- String/Reverse_String_Variation/readme.txt
- String/Reverse_String_Variation/solution.py
> fixes issue-65

- String/check_pangram.py
I have added the program to check if given string is pangram or not.
Fixes issue #59
> Pangram  added

- Data Structures/Stack.py
I've added code for stack implementation with proper comments and explanation. issue #58
> Add Stack Implementation

- Algorithms/Sorting/Dutch_National_Flag.py
Fixed Issue #31 
I tried to make sure file changed is one
Here's a try to fix #106 request
Sorry for the inconvenience
> Dutch National Flag

- Geometry/convexhull.py
This PR is for the issue#34 i.e. The Geometry Program(Covex Hull)
> Added the code for convex hull problem

- Algorithms/Searching/binarysearch_recursion.py
Added binary search for sorted array.
Resolving issue #51
> binarysearch added

- Algorithms/Sorting/Heap_Sort.py
Fixes #73 
Added Heap Sort which uses a heap tree to sort a list of numbers
> Added Heap Sort

- Algorithms/Searching/linear_search.py
- Search/Linear_Search.py
Issue no : #93
Linear Search Program  Added in  a new Folder Search
TestCase 1:
Input some numbers : 5 4 1 3 2
Enter element to search : 3
Element is found at position 3
> Added Linear Search #93

- Topic Wise Questions with Solutions/Array/move_negative_before_positive.py
> fix driver function.

- README.md
- String/concatenate_two_strings.py
One file of Python is added i.e. Concatenation of two strings using Python.
Also updated Readme file.
Issue number: #150
> Concatenation of two strings using Python. Issue:#150

- Algorithms/Sorting/Wiggle_sort.py
> Added wiggle sort

- Algorithms/Searching/Fibonacci_Search.py
#177 
I have added Fibonacci_Search in searching algo folder. 
So please check and accept PR.
> Added Fibonacci_Search

- Topic Wise Questions with Solutions/Recursion/Tiling_Problem.py
Fixed issue #67 
Hope the changes are fine now.
Sorry for the inconvenience .
> Tiling Problem(Recursion)

- Algebra/Armstrong_number.py
> Added the code for Armstrong number problem

- Graphs/Bellmanford-algo.py
issue #195 task-1 Done
implemented Bellmanford algorithm
> implemented BellmanFord Algorithm

- Algebra/Automorphic_number.py
Added Automorphic number
#208 
Do review the PR and merge @rcoder23
> Automorphic Number

- Topic Wise Questions with Solutions/Array/Matrix_Transpose.py
Fixed issue #160 
Please review and suggest if any changes required.
Hoping for a feedback soon.
Thank you for letting me work for this issue.
> Matrix Transpose(2D Arrays)

- Graphs/breadthfirstsearch-algo.py
issue #195 task-2 done
implementation of breadth-first search algorithm
> Issue #195 bfs

- Topic Wise Questions with Solutions/Recursion/Tower_of_hanoi.py
> Tower of Hanoi

- Algorithms/Sorting/shell_sort.py
Fixes #192 
@Joshitha18  @rcoder23  Kindly review my PR.
> Added shell_sort.py

- Algebra/Sieve_Of_Atkins.py
Added the code for the Sieve_Of_Atkins
Resolving the issue (#89 )
> Sieve_Of_Atkins(#89)

- Topic Wise Questions with Solutions/Array/intersection_sortedarray.py
- Topic Wise Questions with Solutions/Array/union_sortedarrays.py
I have contributed the code for union and intersection of two sorted arrays under topic wise questions folder.
I have included clear comments, time and space complexity and sample test case.
Do have a look at the code and let me know the changes if any.
i would like to resolve the issue #82 
Thank you!
> Union and Intersection of sorted arrays

- Data Structures/Binary_Search_Tree.py
- Topic Wise Questions with Solutions/Binary_Search_Tree/maximum_minimum_BST.py
Made all the necessary changes that was asked for issue #19 
Guess it should be fine now
Tried fixing the problem in Request #108 
@rcoder23 @Joshitha18 let me know if any further changes required
> Implemented Binary Search Tree wtih Standard Problems

- Numerical/neon.py
I have added the program to check neon number .Fixes issue #122
> Neon number added

- README.md
- String/RabinKarpStringMatching.py
Also updated the README.md file to include Rabin-Karp algorithm
(This PR corresponds to issue #98)
> Added Rabin-Karp string searching algorithm (Issue #98)

- Dynamic Programming/climbing_stairs.py
> adding climbing stairs

- String/length_of_last_word.py
I have added the program which calculates the length of last word in a string.
Fixes issue #130
> Length of last word program added

- Data Structures/Queue.py
- Data Structures/Stack.py
This is code for queue implementation. issue #126
> Queue Implementation

- Algebra/Euclid_algo_GCD.py
Implemented Euclidian Algorithm for finding GCD
#161 
Output : 
1. 
2.
> Euclidian Algorithm for finding GCD

- Algebra/Interesting_xor.py
Done the code for issue #218 
Do review and merge @rcoder23 @Joshitha18
> Added Interesting XOR

- Algebra/Power of Three.py
Solved issue #247 
Description:
Python source code of the Power of Three problem with a little description.
> Create Power of Three.py

- Topic Wise Questions with Solutions/codechef/ATM.py
@rcoder23 Sir I added code in topic wise folder . I presume now it's fine . Please review this pr under issue #128 .
> Added atm code in topic wise folder

- Algorithms/Sorting/Selection_Sort.py
Solves issue #216.
@rcoder23  @Joshitha18 please review.
> Added Selection Sort

- Topic Wise Questions with Solutions/Array/merge_two_sorted_array_without_extra_space.py
> merge two sorted array without using extra space

- Topic Wise Questions with Solutions/codechef/Fit squares in Triangle.py
I added code for issue #205 in topic wise questions folder under codechef directory . Please review it .
> Added code for fit squares in triangle under issue-205

- Algebra/Magic_Number.py
Added #237 
Do review and merge @rcoder23 @Joshitha18
> Added Magic Number

- Dynamic Programming/painting_fence.py
Fixes #235 
Kindly review my PR @rcoder23  @Joshitha18
> Added Painting Fence algorithm

- Graphs/Kruskal's_Algorithm_Implementation.py
- Graphs/Prim's_Algorithm_Implementation.py
Prim's and Kruskal's minimum spanning tree algorithms
> Added Prim's and Kruskal's Graph MST algorithms

- Algorithms/Sorting/RadixSort.py
This is code for Radix Sort with proper comments and explanation. issue #276
> Radix Sort

- Graphs/Dijsktra's_Algorithm_Implementation.py
I have added Dijkstra's shortest path Algorithm with respect to issue #297
> Added Dijkstra's Shortest Path Algorithm

- Topic Wise Questions with Solutions/Stack/Largest_rectangle_in_Histogram.py
This PR fixes issue #238 
Please review it soon and suggest if any changes are required.
Thank you for assigning me this issue.
> Largest Rectangle in a Histogram

- Topic Wise Questions with Solutions/Recursion/Count_Inversion.py
This PR fixes issue #241 
Please review and suggest if any changes required.
Thank you for letting me work on it.
> Count Inversion

- Algebra/Divisor_Count.py
Added program to count total number of divisors of an integer
> Counting total number of divisors of an integer

- Topic Wise Questions with Solutions/Linked List/Detect_loop_LL.py
The python script show the implemention of a loop detection function in a Singly Linked List.
Solves Issue #310
> Detect loop in Linked List

- Algebra/Pronic_number.py
- README.md
I have added Pronic Number program in python in Algebra section.
Solves: #335
> Pronic Numbers Added

- Topic Wise Questions with Solutions/Array/Subarray_with_sum0.py
Yes I read 
Adding the file Topic Wise Questions with Solutions/Array/Subarray_with_sum0.py
#356
> Topic Wise Questions with Solutions/Array/Subarray_with_sum0.py

- Graphs/Kosaraju_Algorithm_for_Strong_Connected_Components.py
This is code for Kosaraju Algorithm for Strong Connected Components. Issue #347
> Kosaraju Algorithm for Strong Connected Components.

- Algebra/Happy_Number.py
Added the code for checking the number is Happy number or not
Resolved Issue- #324
> Checking number is happy number or not

- Topic Wise Questions with Solutions/Array/Trapping_The_Water.py
yes I have read it.
adding the file in Master-PyAlgo\Topic Wise Questions with Solutions\Array\Trapping_The_Water.py
#374
> Trapping the Water

- String/Knutt_Morris_Prat.py
Fixes #250 
Do review @rcoder23
> Knutt Morris Prat Algorithm

- Algebra/Decagonal_Number.py
> Added Decagonal Number

- Algebra/Sine_Function.py
Added an algorithm capable of calculating the sine function of an angle.
fixes: #145
> Sine Function

- Data Structures/Double_ended_queue.py
@rcoder23 I have changed the location of the file. Kindly check. This resolves the #380 issue. Thank you.
> Double Ended queue

- Algebra/Majority_Element.py
- Topic Wise Questions with Solutions/Array/Majority_Element.py
> Added Majority element

- Algebra/Tribonacci_Number.py
> Added Tribonacci Number

- Topic Wise Questions with Solutions/Linked List/MergeSort LinkedList.py
> Merge sort --> Closes : [#381]

- Numerical/Special.py
> Special Number

- Algebra/Noble_Integer.py
> Added Noble Integer

- Topic Wise Questions with Solutions/Array/Maximum_Product_Subarray.py
Yes 
I came with a fast and efficient way to solve this problem 
#398
> Maximum product subarray 

- Graphs/Warshall.py
Added the code for warshall algorithm in the graphs section.
Fixes #418 
@rcoder23 Kindly review it.
> Warshall Algorithm

- Algebra/Bitwise_AND.py
I've added the complete program with proper comments, example and explanations. @rcoder23 please check out this PR with reference to issue #410.
> Added Program for 'Bitwise AND' 

- Data Structures/SegmentTree_With_LazyPropagation.py
Fixes #433 
Do review @rcoder23 
Added Segment tree with lazy propagation
> Added Segment Trees with Lazy Propagation

- README.md
- String/Initials_of_name.py
Also updated the README.md file to include Initials of name.
(This PR corresponds to issue #386)
> Added Inititals_of_name in string

- Topic Wise Questions with Solutions/Array/count_pair_with_given_sum.py
Master-PyAlgo\Topic Wise Questions with Solutions\Array\count_pair_with_given_sum.py
#440
> Count Pair with given sum

- Data Structures/SegmentTree_RMQ.py
Fixes #433 
Done Segment Trees 
Do review @rcoder23
> Added RMQ Segment Tree

- Data Structures/Fenwick_Tree.py
> Added Fenwick Tree

- Algebra/Table_of_a_Number.py
I've added the complete program with proper comments, example and explanations. @rcoder23 please check out this PR with reference to issue #465.
> Table of a Number

- Data Structures/Circular_Singly_Linked_List.py
Fixes #464 
@rcoder23 
I have added the code of circular singly linked list
Do review and merge
> Circular Singly Linked List

- Data Structures/Tree_Inorder_Preorder_Traversal.py
Fixes #464 
@rcoder23 
Do review and merge
> Tree Inorder and Preorder Traversal

- Topic Wise Questions with Solutions/Array/Hourglass_Sum.py
I've added the complete program with proper comments, example and explanations. @rcoder23 please check out this PR with reference to issue #467.
> Hourglass Sum 

- Topic Wise Questions with Solutions/Array/Next_premutation.py
Yes
Check if the arr is smaller than 2 return the arr same if the array element start larger value then inverse the array, checking the value  larger value swap the position with a smaller element
#397
> add Next Premutation file

- String/Palindrome_Checker.py
I've added the complete program with proper comments, example and explanations. @rcoder23 please check out this PR with reference to issue #415.
> Added Program for 'Palindrome Checker'

- Data Structures/Right_View_Binary_Tree.py
> Right View Binary Tree

- Data Structures/Priority.py
Fixes #480 
@rcoder23 Kindly review it.
> Priority queue

- greedy algorithms/huffman-coding.py
hey @rcoder23
fixes #488 
added huffman coding
> added huffman coding

- greedy algorithms/Eqyption_Fraction.py
hey @rcoder23 
fixes #488 
added egyption fraction
> added egyption fraction

- README.md
- String/Longest_prefix_suffix.py
Added Longest prefix and suffix and also updated readme.md
Fixes: #358
> longest prefix suffix added

- Topic Wise Questions with Solutions/Backtracking/Subset_Sum.py
This PR is with reference to issue #588.
> Subset Sum

- Topic Wise Questions with Solutions/Array/TripletSumValue.py
Adding the file  Master-PyAlgo\Topic Wise Questions with Solutions\Array\TripletSumValue.py
Yes
> Triplet sum Value

- Topic Wise Questions with Solutions/Backtracking/Sudoku.py
This PR is with reference to issue #590.
> Sudoku Game Solving

- Topic Wise Questions with Solutions/Linked List/remove.py
@rcoder23  I added the required code for the #340 . Please review it and let me know any changes to be made.
> Added the required code

- greedy algorithms/fractional_knapsack.py
hey @rcoder23
fixes #488 
added fractional knapsack
> added fractional knapsack

- greedy algorithms/Activity_Selection_problem.py
hey @rcoder23 
fixes #488 
added activity seclection problem
> added activity selection problem

- Topic Wise Questions with Solutions/Array/climbing-the-leaderboard.py
#493  
Adding the file Master-PyAlgo\Topic Wise Questions with Solutions\Array\climbing-the-leaderboard.py
> climbing the leaderborad

- Algorithms/Searching/Breadth_First_Search.py
This PR is with reference to issue #570.
> Breadth First Search

- Topic Wise Questions with Solutions/Array/Minimize_the_Heights.py
yes 
Adding the file in the  Master-PyAlgo\Topic Wise Questions with Solutions\Array\Minimize_the_Heights.py
> add Topic Wise Questions with Solutions/Array/Minimize_the_Heights.py

- Topic Wise Questions with Solutions/Backtracking/Knight's_Tour.py
This PR is with reference to issue #584.
> Knight's Tour

- Topic Wise Questions with Solutions/Backtracking/Hamiltonian_Cycle.py
This PR is with reference to issue #582.
> Hamiltonian Cycle

- Algorithms/Sorting/Insertion_Sort.py
Insertion Sort Code
Issue #596
> Issue -#596

- Graphs/BipartiteGraph.py
- README.md
Fixes------>#594
Check it
@rcoder23
> Bipartite Graph

- Topic Wise Questions with Solutions/Backtracking/Graph_Coloring_Problem.py
This PR is with reference to issue #580.
> Graph Coloring Problem

- String/Word_Score.py
This PR is with reference to issue #578.
> Word Score

- Algebra/Valid_Regex.py
This PR is with reference to issue #576.
> Valid Regex

- String/Unsort_String.py
This PR is with reference to issue #574.
> Unsort String

- Algorithms/Searching/8_Puzzle_Problem_using_BFS.py
This PR is with reference to issue #568.
> 8 Puzzle Problem using BFS

- Algorithms/Searching/8_Puzzle_Problem_using_A_star_Algorithm.py
This PR is with reference to issue #566.
> 8 Puzzle Problem using A* Algorithm

- Algebra/Symmetric_Difference.py
This PR is with reference to issue #560.
> Symmetric Difference

- String/String_Formatting.py
This PR is with reference to issue #556.
> String Formatting

- Algebra/Polynomial_Verification.py
This PR is with reference to issue #550.
> Polynomial Verification

- String/Capitalizing.py
This PR is with reference to issue #547.
> Capitalizing

- String/Occurrence.py
> Occurrence of x in the given sequence

- Algebra/list_sort.py
> List sort on the basis of tuple

- Topic Wise Questions with Solutions/Binary_Search_Tree/BST_Level_Order_Traversal.py
This PR is with reference to issue #506.
> Level Order Traversal of BST

- Algebra/Leap_Year.py
This PR is with reference to issue #517.
> Leap Year Checker

- Topic Wise Questions with Solutions/Linked List/Removing_Duplicacies.py
This PR is with reference to issue #509.
> Removing Duplicates from Linked List
